AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Stack for Running ElasticBeanstalk with Auto Scaling and Configurable Parameters.

Parameters:
  ApplicationName:
    Type: String
    Description: Name of the Elastic Beanstalk Application

  EnvironmentName:
    Type: String
    Description: Name of the Elastic Beanstalk Environment

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the existing VPC

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The IDs of the existing subnets

  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type for the Elastic Beanstalk environment

  MinSize:
    Type: Number
    Default: 1
    Description: Minimum size of the Auto Scaling group

  MaxSize:
    Type: Number
    Default: 3
    Description: Maximum size of the Auto Scaling group

  ApplicationSourceBucket:
    Type: String
    Description: S3 bucket name where the application code is stored

  ApplicationSourceKey:
    Type: String
    Description: S3 key (path) to the application code

  SolutionStackName:
    Type: String
    Default: "64bit Amazon Linux 2 v3.5.14 running PHP 8.1"
    Description: Solution stack name for the environment
    AllowedValues:
      - "64bit Amazon Linux 2 v3.5.14 running PHP 8.1"
      - "64bit Amazon Linux 2 v3.5.14 running Python 3.8"
      - "64bit Amazon Linux 2 v3.5.14 running Node.js 14"
      - "64bit Windows Server 2019 v3.5.14 running IIS 10.0"
      # Add more options as required

Resources:
  ElasticBeanstalkApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: !Ref ApplicationName

  ElasticBeanstalkIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth"
        - "arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkWebTier"
        - "arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkWorkerTier"

  ElasticBeanstalkInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref ElasticBeanstalkIAMRole

  ElasticBeanstalkConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref ApplicationName
      OptionSettings:
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: !Ref MinSize
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: !Ref MaxSize
        # ... [Other settings]
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: !Ref VPCId
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: !Join [ ",", !Ref SubnetIds ]
      SolutionStackName: !Ref SolutionStackName

  ElasticBeanstalkEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref ApplicationName
      EnvironmentName: !Ref EnvironmentName
      TemplateName: !Ref ElasticBeanstalkConfigurationTemplate
      VersionLabel: InitialVersion
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: S3_BUCKET
          Value: !Ref ApplicationSourceBucket
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: S3_KEY
          Value: !Ref ApplicationSourceKey

Outputs:
  ApplicationURL:
    Description: "URL of the Elastic Beanstalk application"
    Value: 
      Fn::GetAtt: 
        - ElasticBeanstalkEnvironment
        - EndpointURL
  EnvironmentId:
    Description: "ID of the Elastic Beanstalk environment"
    Value: 
      Ref: ElasticBeanstalkEnvironment
